### ISSUE TITLE
You can skip the "night" at day time

### ISSUE THREAD

**Issue by studkid** [Lavariator/BetterSleep#1]
**Minecraft Version:** 1.15.2
**Plugin version:** BetterSleep-1.2
**Server Version:** Paper 237

**Description**
-----------------------------------
Players can right click the bed at daytime to increase the percentage counter, if it meets the percentage threshold the day is still skipped, even though it's not night yet.  Also has the side effect of allowing players to spam chat with "[player] entered the bed" as much as they want

**Steps to Reproduce**
-----------------------------------
1. Right click a bed at daytime to give the announcement which also adds to the percentage
2. If enough players also do this, the time is reset to the beginning of the day.

**Comment by silasporth** [comment]
Thank you for report this is now fixed with version 1.2.1.
😃
