### ISSUE TITLE
Night skips if player explodes bed in nether

### ISSUE THREAD

**Issue by r4ndomlog** [Lavariator/BetterSleep#2]
The plugin thinks a player is sleeping in a bed if a bed is right clicked and blown up in the nether. 
https://streamable.com/b9glsv

We use this plugin so that only 1 person needs to sleep to skip the night.

**Comment by r4ndomlog** [comment]
A fix for this would be to just not check beds if they are in the nether

**Comment by silasporth** [comment]
Thanks for your bug report, i will try to fix it as soon as possible.

**Comment by silasporth** [comment]
This bug should now be fixed with update 1.2.2
